<script src="<?= urlOf('assets/vendors/js/vendor.bundle.base.js')?>"></script>
<script src="<?= urlOf('assets/vendors/chart.js/Chart.min.js')?>"></script>
<script src="<?= urlOf('assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js')?>"></script>
<script src="<?= urlOf('assets/vendors/progressbar.js/progressbar.min.js')?>"></script>
<script src="<?= urlOf('assets/js/off-canvas.js')?>"></script>
<script src="<?= urlOf('assets/js/hoverable-collapse.js')?>"></script>
<script src="<?= urlOf('assets/js/template.js')?>"></script>
<script src="<?= urlOf('assets/js/settings.js')?>"></script>
<script src="<?= urlOf('assets/js/todolist.js')?>"></script>
<script src="<?= urlOf('assets/js/dashboard.js')?>"></script>
<script src="<?= urlOf('assets/js/Chart.roundedBarCharts.js')?>"></script>